### ISSUE TITLE
plan 9, pre-go1.5 windows support

### ISSUE THREAD

**Issue by kardianos** [dchest/safefile#4]
On plan 9, os.Rename will not (currently) overwrite an existing file.
On windows before go1.5, os.Rename will not overwrite an existing file.

This might be a go issue rather then a safefile issue.

**Comment by dchest** [comment]
Thank you, it looks like it's impossible to guarantee atomic saving on Windows.

**Comment by dchest** [comment]
Any suggestions on what I should go? Delete destination file on Windows and Plan 9, potentially losing it? Rename existing file to destination to another temporary name, rename temporary file, and delete the renamed original?

**Comment by dchest** [comment]
What do you think about this PR https://github.com/dchest/safefile/pull/5 ?
